services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - cert-volume:/etc/letsencrypt/
      #- cert-volume:/var/lib/letsencrypt/
      - cert-volume:/var/log/letsencrypt/
    command: certonly --standalone -d $site_address -m $cert_email --agree-tos --no-eff-email
    ports:
      - "80:80"
    restart: "no"

  flask_server:
    build: .
    depends_on:
      certbot:
        condition: service_completed_successfully
    container_name: betting_app
    volumes:
      - cert-volume:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"

volumes:
  cert-volume:
