services:
  betting-client:
    build: ./BettingClient/
    container_name: betting-client
    volumes:
      - ${instance_directory}:/BettingInstance/      
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config.json:/usr/share/nginx/html/config.json:ro
      - ./config.json:/usr/share/nginx/html/hu/config.json:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      betting-server:
        condition: service_healthy

  betting-server:
    build: ./BettingServer/
    container_name: betting-server
    volumes:
      - ${instance_directory}:/BettingInstance/
