services:
  nginx_server:
    image: nginx
    container_name: http_server

    volumes:
      - betting-volume:/BettingInstance/
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro      
      - ./app/:/BettingApp/app/:ro
     
    ports:
      - "80:80"
      - "443:443"
    
    depends_on:
      flask_server:
        condition: service_healthy

  flask_server:
    build: .
    container_name: betting_app
    volumes:
      - betting-volume:/BettingInstance/

volumes:
  betting-volume:
