ARG NODE_VERSION=latest
ARG NGINX_VERSION=latest

FROM node:${NODE_VERSION} AS builder

WORKDIR /app
COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/root/.npm npm ci

COPY . .

ARG CONFIGURATION=standard

RUN if [ "$CONFIGURATION" = "low-mem" ] ; then \
        echo "Running throttled Low-Memory/Low-CPU Build..." && \
        node --max-old-space-size=450 ./node_modules/@angular/cli/bin/ng build --configuration=production --output-path=dist/en --base-href="/" --max-workers=1 --source-map=false && \
        node --max-old-space-size=450 ./node_modules/@angular/cli/bin/ng build --configuration=hu-build --output-path=dist/hu --base-href="/" --max-workers=1 --source-map=false ; \
    else \
        echo "Running standard Unthrottled Build..." && \
        npx ng build --configuration=production --output-path=dist/en --base-href="/" && \
        npx ng build --configuration=hu-build --output-path=dist/hu --base-href="/" ; \
    fi

FROM nginx:${NGINX_VERSION} AS runner

EXPOSE 80
EXPOSE 443

COPY --chown=nginx:nginx --from=builder /app/dist/en/browser/. /usr/share/nginx/html/en
COPY --chown=nginx:nginx --from=builder /app/dist/hu/browser/hu/. /usr/share/nginx/html/hu

ENTRYPOINT ["nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
