name: Compose Docker Images
run-name: Compose Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install the application (compose the images)
        run: |
          sudo mkdir -p /BettingInstance
          sudo cp ${{ github.workspace }}/.github/test-config.json /BettingInstance/configuration.json
          chmod +x ${{ github.workspace }}/install.sh
          sudo -E launch_mode=1 client_mode=1 instance_directory=/BettingInstance/ standard_modifier="-f ${{ github.workspace }}/docker-compose.yml -f ${{ github.workspace }}/.github/local-cert.yml" ${{ github.workspace }}/install.sh

      - name: Test the client
        run: |
          sleep 2
          status=$(curl -o /dev/null -k -s -w "%{http_code}" https://localhost/)
          echo "HTTP Status: $status"
          if [ "$status" -ne 200 ]; then
            echo "Request failed with status $status"
            exit 1
          fi

      - name: Test the server
        run: |
          sleep 2
          status=$(curl -o /dev/null -k -s -w "%{http_code}" https://localhost/api/status)
          echo "HTTP Status: $status"
          if [ "$status" -ne 200 ]; then
            echo "Request failed with status $status"
            exit 1
          fi 

      - name: Print logs
        run: |
          docker logs betting-client
          docker logs betting-server

      - name: Stop Docker Images
        run: |
          docker container stop betting-client
          docker container stop betting-server
